apiVersion: v1
kind: ConfigMap
metadata:
  name: global-env
  namespace: i-commerce
data:
  MONGO_COLLECTION_PRODUCTS: products
  MONGO_COLLECTION_FILES: files
  MONGO_COLLECTION_ACTIVITIES: activities
  PORT: "8080"